### ISSUE TITLE
Add Best Practises to README.md

### ISSUE THREAD

**Issue by yatna** [systers/macc#126] opened 2017-02-23 15:41 UTC
I intend to add PR Best Practices  to the README.md. These will include instructions for the contributors to make a better PRs. Something like these-

1  Use meaningful commit messages
2  Do not over commit. (Do not include multiple commits for a small change)
3  Do not add the merge commits to the PR
4 Usually use a single commit for a single issue, unless the issues are related or contain a significant code change.
5 When sending a PR have an appropriate title referencing the issue which it solves.
6  If it is a UI change, add a screen shot of the new/fixed UI.
7  Have a short description on what has gone wrong (like a root cause analysis and description of the fix), if that information is not already present in the issue.

@medhach Can I send a PR?

**Comment by mish24** [comment] 2017-02-23 15:45
@yatna I just added these in #124. Duplicate of #102

**Comment by yatna** [comment] 2017-02-23 16:56
@mish24 Yeah, I created this issue after going through your PR only, as I felt some of these points were missing and could be added to it.

**Comment by mish24** [comment] 2017-04-09 07:39
@medhach Done. Please close.

**Closed as completed** 2017-08-28 13:21 UTC
